### ISSUE TITLE
New property tax classes in 2021?

### ISSUE THREAD

**Issue by AbahlsCMAP** [ccao-data/ptaxsim#30]
The database includes a few parcels in tax year 2021 that have classes that are not in the [assessor class code](https://github.com/ccao-data/ptaxsim/files/14641558/classcode.1.pdf) documentation. 

Specifically:
-  pin 16151020170000 has a class of 192 (though in the [parcel search](https://www.cookcountyassessor.com/pin/16151020170000) it shows 190) 
- and pin 32091000160000 has a class of 826 (and still has a class of 826 in the [parcel search](https://www.cookcountyassessor.com/pin/32091000160000)) 

Can you please clarify whether these classes are accurate in the database and, if so, provide more information about the classes (i.e. name and assessment ratio)? 

My query was "select pin, class, tax_code_num, av_clerk from pin where year = 2021"

Thanks!

**Comment by dfsnow** [comment]
Hi @AbahlsCMAP!

It looks someone fat fingered the class of that first PIN. It's fixed in the system of record but not in the backend DB that populates PTAXSIM. I've opened an issue (https://github.com/ccao-data/ptaxsim/issues/31) to add checks for stuff like this. I'll update that specific PIN on the next minor DB update.

As for 32091000160000, I believe 826 is a commercial greenhouse with some sort of incentive. I'm not super familiar with commercial properties, but if I recall correctly class 8 is assessed at 10% of market for 10 years after the incentive is approved by a local municipality.
